# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170316_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7\u7801'),
        ),
    ]
