# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': '\u67e5\u8be2\u64cd\u4f5c', 'verbose_name_plural': '\u67e5\u8be2\u64cd\u4f5c'},
        ),
    ]
